Feature/goose#4
We-LGD/ddoon-ddoon pull request #16
Opened 2024-12-01 14:57 UTC by KIMGEUNDU

### 구현 내용
**주요 기능**: 공통컴포넌트 Slide 작업

### 스크린샷/기타 자료
![Slide](https://github.com/user-attachments/assets/4a2492ac-b6b5-4564-9bc6-fceb06575bc0)

2024-12-01 15:54 UTC, parkjooyoung0608 requested changes
리뷰 확인하고 수정해줘!

2024-12-01 15:54 UTC, parkjooyoung0608 commented on src/shared/components/atoms/Button.tsx
> +//
불필요한 주석이 달린 것 같아!

2024-12-01 15:54 UTC, parkjooyoung0608 commented on src/shared/components/atoms/Button.tsx
> +  const [isClicked, setIsClicked] = useState(false);
클릭 상태는 외부에서 받아야하지않을까?!
예를 들어 
```
function Button(isClicked){
  onClick={isClicked}
}
```
이런식으로! (이렇게 하라는건 아니고 예시일 뿐! 참고만 해줘)

내부에서 state로 클릭 상태를 받는다면 다른 컴포넌트에서 사용할때 클릭이 됐는지, 안됐는지 알 수가 없어ㅠㅠ

2024-12-01 15:54 UTC, parkjooyoung0608 commented on src/shared/components/atoms/Button.tsx
> +      // disabled
주석은 삭제해주세용

2024-12-01 15:54 UTC, parkjooyoung0608 commented on src/shared/components/organisms/ChallengeBox.tsx
> +import { useState } from 'react';
중요도 순으로 라인 정리해주면 좋을 것 같아!
라이브러리 -> 컴포넌트 -> Utils -> Type 이런식으로!

2024-12-01 15:54 UTC, parkjooyoung0608 commented on src/pages/Main.tsx
해당 내용의 commit 은 스타일을 변경하는 것이 아닌 내용 삭제이기 때문에 style 보다는 chore 가 더 맞을 것 같아!

2024-12-02 15:45 UTC, parkjooyoung0608 commented on src/shared/components/atoms/Button.tsx
> +      // disabled
함수 이름도 통일하면 좋을꺼같아!

지금은 `handleClick` 로 되어있는데 아래에 
```
const failEvent = () => {
    setFail(!fail);
  };

```
얘는 `failEvent`로 되어있더라고!

사용자가 event 를 동작하도록 하는건 handleClose 같이 handle을 붙여주는게 깔끔한거 같은데 어때?

2024-12-02 15:47 UTC, parkjooyoung0608 commented on src/shared/components/atoms/CloseBtn.tsx
> +interface FailProps {
interface는 shared/interface/atomsType.ts 에 올려줘용

2024-12-03 11:41 UTC, KIMGEUNDU commented on src/shared/components/atoms/Button.tsx
> +//
Fetrue/goose#3에서 수정했습니당

2024-12-03 11:41 UTC, KIMGEUNDU commented on src/shared/components/atoms/Button.tsx
> +  const [isClicked, setIsClicked] = useState(false);
Fetrue/goose#3에서 수정했습니당

2024-12-03 11:42 UTC, KIMGEUNDU commented on src/shared/components/atoms/Button.tsx
> +      // disabled
Fetrue/goose#3에서 전역상태로 바꾸면서 변경했습니당

2024-12-03 11:46 UTC, KIMGEUNDU commented on src/shared/components/organisms/ChallengeBox.tsx
> +import { useState } from 'react';
수정했습니다!

2024-12-03 11:46 UTC, KIMGEUNDU commented on src/pages/Main.tsx
넹넹!!

2024-12-03 11:54 UTC, KIMGEUNDU commented on src/shared/components/atoms/CloseBtn.tsx
> +interface FailProps {
수정했습니당

2024-12-03 12:50 UTC, KIMGEUNDU commented on src/shared/components/atoms/Button.tsx
> +      // disabled
이벤트함수명도 수정했습니당

2024-12-03 13:00 UTC, parkjooyoung0608 requested changes

2024-12-03 13:00 UTC, parkjooyoung0608 commented on src/shared/components/atoms/CloseBtn.tsx
import 순서 바꿔주세용
라이브러리 > Type

2024-12-03 13:00 UTC, parkjooyoung0608 commented on src/shared/components/atoms/Button.tsx
> +import useButtonStore from '@/store/useButtonStore';
import 순서 변경해주세용
store > type

2024-12-03 13:02 UTC, KIMGEUNDU commented on src/shared/components/atoms/CloseBtn.tsx
수정했어용!

2024-12-03 13:02 UTC, KIMGEUNDU commented on src/shared/components/atoms/Button.tsx
> +import useButtonStore from '@/store/useButtonStore';
수정했어용!

2024-12-03 13:03 UTC, parkjooyoung0608 approved these changes

2024-12-03 13:04 UTC, merged