feat: Button 컴포넌트 작업
We-LGD/ddoon-ddoon pull request #18
Opened 2024-12-01 15:00 UTC by KIMGEUNDU

### 구현 내용
**주요 기능**: Button 컴포넌트 작업
**디자인/구현상의 결정 사항**
- isClicked라는 `boolean`값 상태를 받음

### 스크린샷/기타 자료
**클릭시 마다  상태 변화**
![Button_cklick](https://github.com/user-attachments/assets/b49ab650-a42b-4a6c-9e0c-dfff7b7b7efb)

**비활성화 상태**
![Button_disabled](https://github.com/user-attachments/assets/6ae83a03-5958-49eb-b82a-b2a5dd8666b9)

2024-12-01 15:58 UTC, parkjooyoung0608 requested changes
수정 내용 확인해줘!

2024-12-01 15:58 UTC, parkjooyoung0608 commented on src/shared/components/atoms/Button.tsx
> +function Button() {
Button은 외부에서 사용하는 컴포넌트이기 때문에 내부에서 상태확인을 하면 안될 것 같아!
외부에서 상태를 받을 수 있도록 수정해줘!

2024-12-01 15:58 UTC, parkjooyoung0608 commented on src/shared/components/atoms/Button.tsx
> +      // disabled
불필요한 주석은 삭제해줘!

2024-12-03 11:37 UTC, KIMGEUNDU commented on src/shared/components/atoms/Button.tsx
> +      // disabled
주석 삭제했어용!

2024-12-03 11:39 UTC, KIMGEUNDU commented on src/shared/components/atoms/Button.tsx
> +function Button() {
외부에서 상태받을 수 있게 zustand로 `useButtonStore`만들었어용!
그리고 각 버튼마다 들어가는 글자가 달라서 `Button`컴포넌트에서는 name, cancel props를 받을 수 있게 수정했습니당
`name`은 버튼에 들어갈 글자이고 `cancel`은 취소버튼일 경우에만 사용해면됩니당

2024-12-03 11:55 UTC, parkjooyoung0608 approved these changes

2024-12-03 11:55 UTC, merged